### ISSUE TITLE
pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:99: void cunn_SpatialClassNLLCriterion_updateOutput_kernel

### ISSUE THREAD

**Issue by liuxuan1988981** [montrealrobotics/ENetDepth#1]
hi, thanks for you code ,but  when I test you  inference.py ues the wright in  file ./save./ enetdepth .  And  have error ,but, I can test the first 8 image  like this: 
could you tell me how it happened.
[Step: 0/5557 (341.22 ms)] Iteration loss: 8.1568
[Step: 1/5557 (292.03 ms)] Iteration loss: 8.1176
[Step: 2/5557 (302.70 ms)] Iteration loss: 8.3072
[Step: 3/5557 (309.85 ms)] Iteration loss: 8.2982
[Step: 4/5557 (349.76 ms)] Iteration loss: 8.2039
[Step: 5/5557 (399.76 ms)] Iteration loss: 8.3238
[Step: 6/5557 (437.54 ms)] Iteration loss: 8.3381
[Step: 7/5557 (463.79 ms)] Iteration loss: 8.2007
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:99: void cunn_SpatialClassNLLCriterion_updateOutput_kernel(T *, T *, T *, long *, T *, int, int, int, int, int, long) [with T = float, AccumT = float]: block: [0,0,0], thread: [252,0,0] Assertion `t >= 0 && t < n_classes` failed.

THCudaCheck FAIL file=/pytorch/aten/src/THC/generated/../THCReduceAll.cuh line=317 error=59 : device-side assert triggered

Traceback (most recent call last):
 File "inference.py", line 365, in <module>
    inference(model, test_loader, w_class, class_encoding)
  File "inference.py", line 290, in inference
    loss, (iou, miou) = test.run_epoch(args.print_step)
  File "inference.py", line 121, in run_epoch

RuntimeError: cuda runtime error (59) : device-side assert triggered at /pytorch/aten/src/THC/generated/../THCReduceAll.cuh:317

**Comment by krrish94** [comment]
This just seems like an error in the label files you're using. They have labels outside the range for which ENet was trained.
