### ISSUE TITLE
GPU Out of Memory Error

### ISSUE THREAD

**Issue by riven314** [montrealrobotics/ENetDepth#2]
I encountered GPU out of memory error when training your model on NYU dataset. As shown below:
![4](https://user-images.githubusercontent.com/21143399/65813106-2a104780-e203-11e9-9b11-28ff8f862762.PNG)

The following is the profile result. It shows that GPU memory usage accumulates rapidly on forward pass:
![2](https://user-images.githubusercontent.com/21143399/65813115-47451600-e203-11e9-82c3-ce0a41324770.PNG)

The following is the configuration of the training:
![3](https://user-images.githubusercontent.com/21143399/65813119-51671480-e203-11e9-9485-66f58ae64ba4.PNG)

GPU Device: GeForce GTX 1080 Ti

Memory error still exists until it is set to 8. But we would like to have a training with larger batch size (~16). Do you have any idea how to make the forward pass more memory efficient? Thank you.

**Comment by krrish94** [comment]
If a switch to a larger memory GPU isn't possible, I'd recommend trying out half precision using NVIDIA Apex. 
https://github.com/NVIDIA/apex

(Overall, you'll need to change 4-5 lines of code, but end up saving ~40% of GPU memory)

**Comment by riven314** [comment]
Thanks for your suggestion!
I also would like to know what GPU device you use for your training? I saw your default batch size is 64. What is the memory size of your GPU device?

**Comment by krrish94** [comment]
If I remember correctly, I used a 32 GB GPU. However, my training image sizes were far lesser (I think 224 x 224)
